name: build
on:
  push:
    branches: [ovirt-engine-build-dependencies-4.5.3.z]
  pull_request:
    branches: [ovirt-engine-build-dependencies-4.5.3.z]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: centos-stream-8

    env:
      ARTIFACTS_DIR: exported-artifacts

    container:
      image: quay.io/ovirt/buildcontainer:el8stream

    steps:
    - name: Checkout sources
      uses: ovirt/checkout-action@main

    - name: Perform build
      run: |
        .automation/build-rpm.sh $ARTIFACTS_DIR

    - name: Upload artifacts
      uses: ovirt/upload-rpms-action@main
      with:
        directory: ${{ env.ARTIFACTS_DIR}}
